keys:
  - &vnb-mb-pro age1hvcmce9e4tkhm2ue2nh7tan6qxy7dewyf8rkentshf20qlt3x5aszkpn7c
  - &jarle age1akwhlc7p3nmvty78nvqj9egdamvt86r6pkljjry9846f5uxju4hsnzr5pq
  # Replace with trond-arne key later
  - &trond-arne age1akwhlc7p3nmvty78nvqj9egdamvt86r6pkljjry9846f5uxju4hsnzr5pq
creation_rules:
  - path_regex: secrets/VNB-MB-Pro.*
    key_groups:
      - age:
          - *vnb-mb-pro
  - path_regex: secrets/Jarle.*
    key_groups:
      - age:
          - *jarle

  - path_regex: secrets/trond-arne.*
    key_groups:
      - age:
          - *trond-arne

  - path_regex: secrets/mods-cli-openai-api\.key
    key_groups:
      - age:
          - *trond-arne
          - *jarle
          - *vnb-mb-pro
  - path_regex: secrets/claude-nvim-api-key\.key
    key_groups:
      - age:
          - *trond-arne
          - *jarle
          - *vnb-mb-pro
