keys: &all
  - &silicon age1hvcmce9e4tkhm2ue2nh7tan6qxy7dewyf8rkentshf20qlt3x5aszkpn7c
  - &argon age1akwhlc7p3nmvty78nvqj9egdamvt86r6pkljjry9846f5uxju4hsnzr5pq
  - &cobalt age12ewxc5y60mgvu240gvjnnc6uufvjrh757kad7dkzlwm64fcd4v4qtmvpy5
  - &helium age102w690dszwe3305vg3v084y6z6hstjsxskatz6evguj3utzz6e4s7yfrfr
  - &fluoride age16fmgfwq6hjyps36ar9jvwj7325sjfju3yfxt9df2zlfwu9dzdudqwpsh9f
  - &utv-vnb-lt age19f0gx25ug7r8gczchncs7hmhvff92rhjn748ednp29j68y3jrffqwkl79k
  - &carbon age1qv3gkg44yhuygegjdke8596hcm0mhe5c2ezqcl4jwsg397lpcf8qd9pn0d
  - &boron age1x9wkzr3hu2vk92nx3q0h0v9amd9v5p44pz3gpecvx88z7kf4ta7qchkjfy
creation_rules:
  - path_regex: secrets/.*\.ssh\.pub
    key_groups:
      - age: *all

  - path_regex: secrets/silicon.*
    key_groups:
      - age:
          - *silicon
  - path_regex: secrets/argon.*
    key_groups:
      - age:
          - *argon

  - path_regex: secrets/cobalt.*
    key_groups:
      - age:
          - *cobalt

  - path_regex: secrets/helium.*
    key_groups:
      - age:
          - *helium

  - path_regex: secrets/fluoride.*
    key_groups:
      - age:
          - *fluoride

  - path_regex: secrets/boron.*
    key_groups:
      - age:
          - *boron

  - path_regex: secrets/utv-vnb-lt.*
    key_groups:
      - age:
          - *utv-vnb-lt
          - *argon

  - path_regex: secrets/carbon.*
    key_groups:
      - age:
          - *carbon

  - path_regex: secrets/building-carbon\.ssh
    key_groups:
      - age:
          - *carbon

  - path_regex: secrets/building-carbon\.ssh\.pub
    key_groups:
      - age:
          - *argon
          - *carbon

  - path_regex: secrets/pub-.*
    key_groups:
      - age: *all
