keys:
  - &silicon age1hvcmce9e4tkhm2ue2nh7tan6qxy7dewyf8rkentshf20qlt3x5aszkpn7c
  - &argon age1akwhlc7p3nmvty78nvqj9egdamvt86r6pkljjry9846f5uxju4hsnzr5pq
  - &cobalt age12ewxc5y60mgvu240gvjnnc6uufvjrh757kad7dkzlwm64fcd4v4qtmvpy5
creation_rules:
  - path_regex: secrets/silicon.*
    key_groups:
      - age:
          - *silicon
  - path_regex: secrets/argon.*
    key_groups:
      - age:
          - *argon

  - path_regex: secrets/cobalt.*
    key_groups:
      - age:
          - *cobalt

  - path_regex: secrets/mods-cli-openai-api\.key
    key_groups:
      - age:
          - *cobalt
          - *argon
          - *silicon
  - path_regex: secrets/claude-nvim-api-key\.key
    key_groups:
      - age:
          - *cobalt
          - *argon
          - *silicon
  - path_regex: secrets/strise-milkyway-translations-openai-api-key\.key
    key_groups:
      - age:
          - *cobalt
          - *argon
          - *silicon
