{ utils, ... }:
{
  # imports = utils.importSubdirs "default.nix" ./.;
  imports = [
    ./machines
    ./machines/Jarle
    ./machines/VNB-MB-Pro
    ./machines/nixos-vm
    ./machines/trond-arne
    ./packages/applications/audio/spotify-player
    ./packages/applications/editors/idea
    ./packages/applications/editors/neovim
    ./packages/applications/editors/nixvim
    ./packages/applications/editors/vim
    ./packages/applications/file-managers/nnn
    ./packages/applications/graphics/gimp
    ./packages/applications/graphics/imagemagick
    ./packages/applications/graphics/xnviewmp
    ./packages/applications/misc/1password
    ./packages/applications/misc/1password-gui
    ./packages/applications/misc/barrier
    ./packages/applications/misc/lutris
    ./packages/applications/misc/neo4j-desktop
    ./packages/applications/misc/notion
    ./packages/applications/misc/obsidian
    ./packages/applications/networking/browsers/vivaldi
    ./packages/applications/networking/cyberduck
    ./packages/applications/networking/discord
    ./packages/applications/networking/filen
    ./packages/applications/networking/slack
    ./packages/applications/terminal-emulators/cool-retro-term
    ./packages/applications/terminal-emulators/kitty
    ./packages/applications/terminal-emulators/wezterm
    ./packages/applications/version-management/gh
    ./packages/applications/version-management/git
    ./packages/applications/version-management/glab
    ./packages/applications/version-management/jujutsu
    ./packages/applications/virtualization/docker
    ./packages/audio/bcn
    ./packages/audio/cava
    ./packages/audio/mpc-cli
    ./packages/core
    ./packages/development/compilers/libgcc
    ./packages/development/libraries/fontconfig
    ./packages/development/tools/fastgron
    ./packages/development/tools/jq
    ./packages/environment/desktop/hyprland
    ./packages/environment/desktop/hyprland/rice
    ./packages/environment/desktop/hyprland/rice/hyprland
    ./packages/environment/small-memory-wallpaper
    ./packages/environment/theme/catppuccin
    ./packages/os-specific/darwin/alt-tab
    ./packages/os-specific/darwin/karabiner-elements
    ./packages/os-specific/darwin/linearmouse
    ./packages/os-specific/darwin/logi-options-plus
    ./packages/os-specific/darwin/openvpn-connect
    ./packages/shells/fish
    ./packages/tools/admin/google-cloud-sdk
    ./packages/tools/filesystem/bat
    ./packages/tools/filesystem/eza
    ./packages/tools/misc/direnv
    ./packages/tools/misc/entr
    ./packages/tools/misc/fd
    ./packages/tools/misc/run-as-service
    ./packages/tools/misc/thefuck
    ./packages/tools/misc/tmux
    ./packages/tools/misc/xclip
    ./packages/tools/misc/zellij
    ./packages/tools/misc/zoxide
    ./packages/tools/networking/curl
    ./packages/tools/networking/ssh
    ./packages/tools/package-management/homebrew
    ./packages/tools/package-management/nix-index
    ./packages/tools/security/gpg
    ./packages/tools/text/fzf
    ./packages/tools/text/gnused
    ./packages/tools/text/gnutar
    ./packages/tools/text/less
    ./packages/tools/text/ripgrep
    ./profiles/core
    ./profiles/core/audio
    ./profiles/core/systemd
    ./profiles/desktop
    ./profiles/desktop/darwin
    ./profiles/desktop/darwin/logitech
    ./profiles/desktop/gaming
    ./profiles/desktop/kvm
    ./profiles/desktop/work
    ./profiles/libraries/fonts
  ];
}
