{ utils, ... }:
{
  # imports = utils.importSubdirs "default.nix" ./.;
  imports = [
    ./machines
    ./machines/Jarle
    ./machines/VNB-MB-Pro
    ./machines/nixos-vm
    ./machines/trond-arne
    ./modules/applications/audio/spotify-player
    ./modules/applications/editors/idea
    ./modules/applications/editors/neovim
    ./modules/applications/editors/nixvim
    ./modules/applications/editors/vim
    ./modules/applications/file-managers/nnn
    ./modules/applications/graphics/gimp
    ./modules/applications/graphics/imagemagick
    ./modules/applications/graphics/xnviewmp
    ./modules/applications/misc/1password
    ./modules/applications/misc/1password-gui
    ./modules/applications/misc/barrier
    ./modules/applications/misc/lutris
    ./modules/applications/misc/neo4j-desktop
    ./modules/applications/misc/notion
    ./modules/applications/misc/obsidian
    ./modules/applications/networking/browsers/vivaldi
    ./modules/applications/networking/cyberduck
    ./modules/applications/networking/discord
    ./modules/applications/networking/filen
    ./modules/applications/networking/slack
    ./modules/applications/terminal-emulators/cool-retro-term
    ./modules/applications/terminal-emulators/kitty
    ./modules/applications/terminal-emulators/wezterm
    ./modules/applications/version-management/gh
    ./modules/applications/version-management/git
    ./modules/applications/version-management/glab
    ./modules/applications/version-management/jujutsu
    ./modules/applications/virtualization/docker
    ./modules/audio/bcn
    ./modules/audio/cava
    ./modules/audio/mpc-cli
    ./modules/core
    ./modules/development/compilers/libgcc
    ./modules/development/libraries/fontconfig
    ./modules/development/tools/fastgron
    ./modules/development/tools/jq
    ./modules/environment/desktop/hyprland
    ./modules/environment/desktop/hyprland/rice
    ./modules/environment/desktop/hyprland/rice/hyprland
    ./modules/environment/small-memory-wallpaper
    ./modules/environment/theme/catppuccin
    ./modules/os-specific/darwin/alt-tab
    ./modules/os-specific/darwin/karabiner-elements
    ./modules/os-specific/darwin/linearmouse
    ./modules/os-specific/darwin/logi-options-plus
    ./modules/os-specific/darwin/openvpn-connect
    ./modules/shells/fish
    ./modules/tools/admin/google-cloud-sdk
    ./modules/tools/filesystem/bat
    ./modules/tools/filesystem/eza
    ./modules/tools/misc/direnv
    ./modules/tools/misc/entr
    ./modules/tools/misc/fd
    ./modules/tools/misc/run-as-service
    ./modules/tools/misc/thefuck
    ./modules/tools/misc/tmux
    ./modules/tools/misc/xclip
    ./modules/tools/misc/zellij
    ./modules/tools/misc/zoxide
    ./modules/tools/networking/curl
    ./modules/tools/networking/ssh
    ./modules/tools/package-management/homebrew
    ./modules/tools/package-management/nix-index
    ./modules/tools/security/gpg
    ./modules/tools/text/fzf
    ./modules/tools/text/gnused
    ./modules/tools/text/gnutar
    ./modules/tools/text/less
    ./modules/tools/text/ripgrep
    ./profiles/core
    ./profiles/core/audio
    ./profiles/core/systemd
    ./profiles/desktop
    ./profiles/desktop/darwin
    ./profiles/desktop/darwin/logitech
    ./profiles/desktop/gaming
    ./profiles/desktop/kvm
    ./profiles/desktop/work
    ./profiles/libraries/fonts
  ];
}
