// Generated by Home Manager.

user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.aboutwelcome.didSeeFinalScreen", true);
user_pref("browser.bookmarks.file", "/nix/store/v37s4x0qc47xlh31501yglxv6arg803n-firefox-bookmarks.html");
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.bookmarks.showMobileBookmarks", true);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.crashReports.unsubmittedCheck.autoSubmit2", true);
user_pref("browser.engagement.ctrlTab.has-used", true);
user_pref("browser.engagement.fxa-toolbar-menu-button.has-used", true);
user_pref("browser.places.importBookmarksHTML", true);
user_pref("browser.search.newSearchConfig.enabled", true);
user_pref("browser.search.region", "NO");
user_pref("browser.urlbar.ctrlCanonizesURLs", false);
user_pref("devtools.everOpened", true);
user_pref("dom.security.https_only_mode", true);
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.trr.mode", 2);
user_pref("network.trr.uri", "https://mozilla.cloudflare-dns.com/dns-query");
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.exposeContentTitleInWindow", false);
user_pref("privacy.exposeContentTitleInWindow.pbm", false);
user_pref("privacy.globalprivacycontrol.enabled", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);



