-- Generated by Stylix
local wezterm = require("wezterm")
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)
local function stylix_wrapped_config()
    local windowsConfig = require 'windows-config'
local baseConfig = {
  hide_tab_bar_if_only_one_tab = true,
  send_composed_key_when_left_alt_is_pressed = true,
  send_composed_key_when_right_alt_is_pressed = false,
  default_cursor_style = 'BlinkingBar',
  -- Disable easing for cursor, blinking text and visual bell
  animation_fps = 1,
}
for k,v in pairs(windowsConfig.config()) do
  baseConfig[k] = v
end
return baseConfig

end
local stylix_base_config = wezterm.config_builder()
local stylix_user_config = stylix_wrapped_config()
stylix_base_config = {
    -- Set due to the default fancy tabs not respecting colorschemes
    -- See https://github.com/wez/wezterm/issues/2615
    use_fancy_tab_bar = false,
    color_scheme = "stylix",
    font = wezterm.font_with_fallback {
        "FiraCode Nerd Font Mono",
        "Noto Color Emoji",
    },
    font_size = 12,
    window_background_opacity = 1.000000,
    window_frame = {
        active_titlebar_bg = "#494d64",
        active_titlebar_fg = "#cad3f5",
        active_titlebar_border_bottom = "#494d64",
        border_left_color = "#1e2030",
        border_right_color = "#1e2030",
        border_bottom_color = "#1e2030",
        border_top_color = "#1e2030",
        button_bg = "#1e2030",
        button_fg = "#cad3f5",
        button_hover_bg = "#cad3f5",
        button_hover_fg = "#494d64",
        inactive_titlebar_bg = "#1e2030",
        inactive_titlebar_fg = "#cad3f5",
        inactive_titlebar_border_bottom = "#494d64",
    },
    command_palette_bg_color = "#1e2030",
    command_palette_fg_color = "#cad3f5",
    command_palette_font_size = 10,
}
for key, value in pairs(stylix_user_config) do
    stylix_base_config[key] = value
end
return stylix_base_config
