{ util, ... }:
util.mkProfile "cli" {
  gipphe.programs = {
    _1password.enable = true;
    atuin.enable = true;
    bat.enable = true;
    btop.enable = true;
    clipboard-jh.enable = true;
    curl.enable = true;
    direnv.enable = true;
    entr.enable = true;
    eza.enable = true;
    fastgron.enable = true;
    fd.enable = true;
    fish.enable = true;
    fzf.enable = true;
    gh.enable = true;
    git.enable = true;
    glab.enable = true;
    gnused.enable = true;
    gnutar.enable = true;
    gpg.enable = true;
    gum.enable = true;
    imagemagick.enable = true;
    jq.enable = true;
    jujutsu.enable = true;
    less.enable = true;
    make.enable = true;
    nh.enable = true;
    nixvim.enable = true;
    nnn.enable = true;
    ripgrep.enable = true;
    serpl.enable = true;
    ssh.enable = true;
    thefuck.enable = true;
    unzip.enable = true;
    vim.enable = true;
    xclip.enable = true;
    yazi.enable = true;
    zellij.enable = true;
    zoxide.enable = true;
  };
}
