-- Generated by Stylix
local wezterm = require("wezterm")
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)
-- Allow working with both the current release and the nightly
local config = {}
if wezterm.config_builder then
  config = wezterm.config_builder()
end
local stylix_base_config = {

    color_scheme = "stylix",
    window_frame = {
        active_titlebar_bg = "494d64",
        active_titlebar_fg = "cad3f5",
        active_titlebar_border_bottom = "494d64",
        border_left_color = "1e2030",
        border_right_color = "1e2030",
        border_bottom_color = "1e2030",
        border_top_color = "1e2030",
        button_bg = "1e2030",
        button_fg = "cad3f5",
        button_hover_bg = "cad3f5",
        button_hover_fg = "494d64",
        inactive_titlebar_bg = "1e2030",
        inactive_titlebar_fg = "cad3f5",
        inactive_titlebar_border_bottom = "494d64",
    },
    colors = {
      tab_bar = {
        background = "1e2030",
        inactive_tab_edge = "1e2030",
        active_tab = {
          bg_color = "24273a",
          fg_color = "cad3f5",
        },
        inactive_tab = {
          bg_color = "494d64",
          fg_color = "cad3f5",
        },
        inactive_tab_hover = {
          bg_color = "cad3f5",
          fg_color = "24273a",
        },
        new_tab = {
          bg_color = "494d64",
          fg_color = "cad3f5",
        },
        new_tab_hover = {
          bg_color = "cad3f5",
          fg_color = "24273a",
        },
      },
    },
    command_palette_bg_color = "1e2030",
    command_palette_fg_color = "cad3f5",
    
    font = wezterm.font_with_fallback {
        "FiraCode Nerd Font Mono",
        "Noto Color Emoji",
    },
    font_size = 12,
    command_palette_font_size = 10,
    
    window_background_opacity = 1.000000,
}
for key, value in pairs(stylix_base_config) do
    config[key] = value
end
local function stylix_wrapped_config()
    local wezterm = require 'wezterm'
local windowsConfig = require 'windows-config'
local linuxConfig = require 'linux-config'
local baseConfig = {
  hide_tab_bar_if_only_one_tab = true,
  send_composed_key_when_left_alt_is_pressed = true,
  send_composed_key_when_right_alt_is_pressed = false,
  default_cursor_style = 'BlinkingBar',
  -- See https://github.com/wez/wezterm/issues/5990
  front_end = "WebGpu",
  -- Disable easing for cursor, blinking text and visual bell
  animation_fps = 1,
  warn_about_missing_glyphs = false,
}

-- Strip Zellij session name from window title
wezterm.on('format-window-title', function(tab, pane, tabs, panes, config)
  local title = tab.active_pane.title
  -- Remove Zellij session name pattern: "session-name | actual-title"
  local stripped = title:match("^[^|]+%|%s*(.+)$")
  if stripped then
    return stripped
  end
  return title
end)

for k,v in pairs(windowsConfig.config()) do
  baseConfig[k] = v
end
for k,v in pairs(linuxConfig.config()) do
  baseConfig[k] = v
end
return baseConfig

end
local stylix_user_config = stylix_wrapped_config()
if stylix_user_config then
    for key, value in pairs(stylix_user_config) do
        config[key] = value
    end
end
return config

