// Generated by Home Manager.

user_pref("browser.urlbar.trimHttps", false);
user_pref("browser.urlbar.trimUrls", false);
user_pref("taskbar.grouping.useprofile", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);



